#Language
#English: en-US, Simplified Chinese: zh-CN, Traditional Chinese: zh-TW
Language: "en-US"

# Teleport Delay (Second)
Delay: 3

# Teleport Cooldown (Second)
Cooldown: 30

# Available World
World:
  - "world"
  - "world_nether"
  - "world_the_end"

# Minimum Teleport Range
MinTeleportX: 250
MinTeleportZ: 250

# Maximum Teleport Range
MaxTeleportX: 500
MaxTeleportZ: 500